pingouin/circular.py
According to Jammalamadaka & Sengupta (2001, pg. 177) the circular means are not well defined if the marginal distribution of one of the angles is uniform. This leads to wrong estimates of circular correlations in these cases. There is an alternative formulation of the circular correlation coefficient that deals with this problem (see equation 8.2.4 in Jammalamadaka & Sengupta, 2001). This implementation can also lead to slightly different values for the coefficient in other cases, though. 
References:
- Jammalamadaka, S. R., & Sengupta, A. (2001). Topics in circular statistics (Vol. 5). world scientific.
=> Circular correlation for uniform marginals

pingouin/external/tabulate.py, pingouin/plotting.py, pingouin/utils.py
*  Import ABC from collections.abc instead of collections for Python 3.9 compatibility.
* Fix deprecation warning due to invalid escape sequences.
=>  Import ABC from collections.abc instead of collections for Python 3.9 compatibility.

pingouin/correlation.py
During my scripts I was entering x/y/covar as the same string in some cases. This led to a strange error downstream which took a little time to trace back to the casue. So I have included these checks as assertions. There may be a better way to do this so that this condition is checked for all functions which require inputs to be independent..Let me know if you think so.
=> Update partial_corr to assert that x/y are independent from covar

pingouin/regression.py
When as_dataframe=False, add arrays containing processed
regression data X, Xw, y, yw, and the model prediction pred to
the output dictionary.
=> Add processed arrays to linear_regression output

pingouin/plotting.py
Instead of overwriting all default kwargs when setting a single element, the default kwargs are now updated, keeping the defaults if not otherwise specified.
In general, I'd say that specifying the defaults in the function definition kwargs could be avoided entirely, but this would require a more thorough refactoring.
If this implementation is ok, I could integrate it for all plotting functions.
=> ENH: plot_paired: update default kwargs instead of overwriting

pingouin/plotting.py, pingouin/tests/test_plotting.py
Added the argument `boxplot_in_front` (default=False to retain standard behavior) to `plot_paired`.
This allows setting the boxplot above the line plots, f.i. for large numbers of subjects. Also added a slight `alpha=.75` to the boxplot patch (but not to the borders) to see the lines below the boxplot.
Example:
```
import numpy as np
import pandas as pd
import dev_pg.pingouin.pingouin as pg
df = pd.DataFrame(
{'id': np.tile(np.arange(100), 2),
'dv': np.random.rand(200),
'wthn': np.concatenate((np.full(100, 'A'), np.full(100, 'B')))})
pg.plot_paired(df, dv='dv', within='wthn', subject='id')
pg.plot_paired(df, dv='dv', within='wthn', subject='id', boxplot_in_front=True)
```
=> ENH: plot_paired: boxplot_in_front argument added to allow setting the boxplot in the foreground

docs/changelog.rst, pingouin/bayesian.py, pingouin/config.py, pingouin/tests/test_bayesian.py, pingouin/utils.py
As discussed in #101.
The lower-level functions `bayesian.bayesfactor_ttest` etc. now return `float`s; all post-processing (i.e., formatting into scientific or positional string) is handled at the DataFrame level in `_postprocess_dataframe`.
=> Implement BF formatting using the new options module

README.rst, docs/changelog.rst, docs/index.rst, pingouin/regression.py, pingouin/tests/test_regression.py
closes #130 
For now I opted to only return the coefficients in case a rank deficient design matrix is detected.
The basic error of pingouin is its inability to handle the `residues` return parameter of `lstsq` whenever the design matrix is rank deficient. In that case, `residues` is an empty array `array([], dtype=float64)` instead of a float.
One option apart from warning and simply returning the coefficients only could be to "revive" the currently commented line from line 413(old) / 422(new): `    # ss_res = (resid ** 2).sum()`
Something like:
```Python
coef, ss_res, rank, _ = lstsq(Xw, yw)
if coef_only:
return coef
calc_ss_res = False
if rank < Xw.shape[1]:
warnings.warn('Design matrix supplied with `X` parameter is rank '
f'deficient (rank {rank} with {Xw.shape[1]} columns. '
'That …
```
=> multiple regression: catch rank deficient design matrices and warn

docs/changelog.rst, pingouin/correlation.py
I noticed a missing safety check in the corr function and add it in this PR.
```python
stat_bnt = pingouin.correlation.corr(
_curdat[colname], _curdat["correct_choice"], method="kendall", tail="two-tailed"
)
```
```python
stat_bnt = pingouin.correlation.corr(
_curdat[colname], _curdat["correct_choice"], method="pearson", tail="two-tailed"
)
```
So the wrong input was sometimes still called, but not always. With my changes, it is always called.
This probably fixes a silent bug: When users used `kendall` as the `method`, and specified `two-tailed` (instead of the correct `two-sided`), no error was raised ... and a one-sided p value was returned :skull: :grimacing: 
see:
https://github.com/raphaelvallat/pingouin/blob/0c3bf73629ffb1826dc298f0ee498e0784222b5e/pingouin/correlation.py#L556
if …
=> [BUGFIX] Add safety check for `tail` argument in corr func

pingouin/correlation.py, pingouin/tests/test_correlation.py
`import pingouin as pg
df = pg.read_dataset('partial_corr')
pg.partial_corr(data=df, x='cv1', y='y', covar=['cv1'])`
This code example gives an error - as it should since x is in covar. However the error message is rather non-intuitive:
```
Traceback (most recent call last):
File "[FILE_PATH]", line 3, in <module>
pg.partial_corr(data=df, x='cv1', y='y', covar=['cv1'])
File "[PYTHON_LIB_PATH]\pingouin\correlation.py", line 759, in partial_corr
return corr(res_x, res_y, method=method, tail=tail)
File "[PYTHON_LIB_PATH]\pingouin\correlation.py", line 509, in corr
assert x.ndim == y.ndim == 1, 'x and y must be 1D array.'
AssertionError: x and y must be 1D array.
```
If covar is a string instead of a list of strings, then one gets this error message
```
Traceback (most recent call last):
File …
```
=> Improved error message of partial_corr when x is in covar

pingouin/regression.py
The docs didn't say how the scikit-learn default solver was changed. Inquiring minds would have to go to the source code. I added the default solver.
=> DOCS add how Logistic Regression is modified to match R and statsmodels

setup.py
The license entry is only supposed to contain the license name, not the full license text. We already have that in the LICENSE file which is included in the package via MANIFEST.in
=> Only put license name in package metadata

docs/changelog.rst, pingouin/distribution.py
This PR solves issue described by https://github.com/scipy/scipy/issues/14816, with solution still not merged in SciPy https://github.com/scipy/scipy/pull/14817.
`gzscore` can be simpy re-written as the zscore of log-values. This implementation is fast, and it inherits from all options available in `zscore`: `axis`, `ddof` and `nan_policy`.
I don't know what is the deprecation policy in pingouin, but since `gzscore` should be available in SciPy 1.8.0, we could add a deprecation warning, to remove it when you will update scipy version in requirements.
=> Improve gzscore

docs/changelog.rst, pingouin/pairwise.py
This PR replaces use of statsmodels' studentized range distribution functions (`statsmodels.stats.libqsturng.qsturng`, `statsmodels.stats.libqsturng.psturng`) with those from SciPy now that `scipy.stats.studentized_range` is available (SciPy 1.7.0+). 
Speed is maintained, and results are more accurate because SciPy's implementation evaluates the integral for the provided arguments rather than interpolating from tabulated results. statsmodels [has adopted](https://github.com/statsmodels/statsmodels/pull/8035) this change internally as well.
For example, this box and whiskey plot (from [here](https://zenodo.org/record/5151976#.YekY3_7MKUk)) compares the relative accuracy of the studentized range CDF in SciPy, statsmodels, and R (ptukey) across a wide range of inputs.
=> ENH: use studentized range over statsmodels for pairwise tests

pingouin/correlation.py, pingouin/pairwise.py, pingouin/parametric.py, pingouin/plotting.py
Fixed the bug from https://github.com/raphaelvallat/pingouin/issues/232
To pass unit tests I also:
Implemented your fix @raphaelvallat from https://github.com/raphaelvallat/pingouin/issues/227
DataFrame.apply() does not copy dtypes for some reason ant it is also deprecated (https://pandas.pydata.org/pandas-docs/version/1.4.0/whatsnew/v1.4.0.html), causing unit tests to fail, so I replaced the following line
https://github.com/raphaelvallat/pingouin/blob/dcfdc82bbc7f1ba5991b80717a5ca156617443e8/pingouin/pairwise.py#L461-L462
with
```py
stats = stats.reindex(stats.index.union(idxiter))
```
=> Fixes for dependency (scipy and pandas) updates

pingouin/plotting.py
It is clear in this case that labels and title are added to an axis object. The call to `scipy._morestats` can therefore be replaced with direct calls of the matplotlib functions.
=> Remove dependency on scipy._morestats

notebooks/04_Correlations.ipynb
the comment spoke about `BMI`, yet the code used `gender`; aligned now
=> better docs: aligned the comment and code

pingouin/bayesian.py, pingouin/tests/test_bayesian.py
Checked to be consistent with http://pcl.missouri.edu/bf-binomial.
=> Allow bayesfactor_binom to take Beta alternative model (#249)

docs/changelog.rst, requirements.txt, setup.py
Temporary fix for #272 
We will need to revert these changes when the next stable version of scikit-learn is released (1.1.2): https://github.com/scikit-learn/scikit-learn/pull/23608
=> Use scikit-learn<1.1.0

docs/changelog.rst, notebooks/01_ANOVA.ipynb, pingouin/power.py, pingouin/tests/test_power.py
Closes https://github.com/raphaelvallat/pingouin/issues/268
=> Renamed eta to eta-squared in power functions

pingouin/nonparametric.py, pingouin/pairwise.py, pingouin/parametric.py, pingouin/plotting.py, pingouin/utils.py
[DataMatrix](https://pydatamatrix.eu/) objects are similar to DataFrame objects and can be easily converted. This PR patches `_check_dataframe()` such that it performs this conversion if necessary, while avoiding unnecessary overhead (such as importing DataMatrix if not necessary). This also opens the door for converting other DataFrame-like objects, such as structured arrays, etc. However, this is not implemented here.)
PS. The linter complains that I should reformat the code. I'm not sure how to fix that, because it's already pep-8 compatible, as far as I can tell (?).
=> Add support for DataMatrix objects

pingouin/multivariate.py, pingouin/tests/test_multivariate.py
For large n, the lognormal variance was given by a function of log(1+x) for x very close to zero. Numpy provides the more stable function log1p(x) to address cases where 1+x = 1 in floating point representations, which would otherwise incorrectly yield log(1+x) = 0.
I added a test to check this case. The previous version of the code failed this check (giving p = nan).
=> Fix numerical stability issue in multivariate_normality

README.rst, docs/changelog.rst, docs/index.rst, notebooks/00_QuickStart.ipynb, notebooks/01_ANOVA.ipynb, pingouin/pairwise.py, pingouin/tests/test_pairwise.py, pingouin/tests/test_utils.py
As discussed in https://github.com/raphaelvallat/pingouin/pull/290, this PR adds the `ptests` (pairwise_ttest) method to pandas.DataFrame to calculate pairwise T-tests between columns of a pandas DataFrame. This can be used as an alternative to the `pingouin.pairwise_tests` function when the data is in wide-format instead of long-format. Unlike the pairwise_tests function, the `ptests` function only return the T-values (lower triangle) and p-values (upper triangle). Please see examples below:
I'm looking for one reviewer to review the PR. Thanks!
```python
>>> import numpy as np
>>> import pandas as pd
>>> import pingouin as pg
>>> # Load an example dataset of personality dimensions
>>> df = pg.read_dataset('pairwise_corr').iloc[:30, 1:]
>>> df.columns = ["N", "E", "O", 'A', "C"]
>>> # …
```
=> Add new function for pairwise T-tests between columns of a dataframe (pingouin.ptests)

pingouin/multivariate.py, pingouin/parametric.py, pingouin/power.py, pingouin/tests/test_multivariate.py, pingouin/tests/test_power.py
Due to a scipy interface change the pairwise_test can fail when obtaining the t-value from a single sample comparison, this, I believe, fixes that issue.
=> Handle single-sample comparsion in pairwise_test

pingouin/tests/test_regression.py
When using the [`pytest-flakefinder`](https://github.com/dropbox/pytest-flakefinder) plugin with the TestRegression module, it fails. To reproduce, run:
`pytest --flake-finder --flake-runs=2 -rP pingouin/tests/test_regression.py::TestRegression`
For context, the flakefinder plugin runs the tests multiple times in a different order each time. This helps us check how robust the tests are. In this case, the tests failed because the two test modules inside `TestRegression`, `test_logistic_regression` and `test_mediation_analysis` were victim tests (defined as per [iFixFlakies](https://mir.cs.illinois.edu/winglam/publications/2019/ShiETAL19iFixFlakies.pdf)). The first test, `test_linear_regression`, was polluting the `df` variable.
More specifically, at least for the `test_logistic_regression` …
=> Change TestRegression class test methods to fix victim flakiness

docs/changelog.rst, pingouin/plotting.py, requirements-test.txt
Hi @raphaelvallat - I love the `plot_rm_corr` function and needed some flexibility to change its scatter and line features (e.g., marker size and line width). I made a simple change to allow this, adding two sets of kwargs that get passed through to seaborn. Nothing about the defaults have changed, it just offers flexibility if desired.
Sorry I didn't open an Issue first, it was just such a straight-forward change I thought I'd go for it. No pressure if you want to reject this idea.
=> Add aesthetic flexibility to plot_rm_corr

docs/changelog.rst, requirements.txt, setup.py
See https://github.com/raphaelvallat/pingouin/pull/278 and https://github.com/scikit-learn/scikit-learn/pull/23608
=> Use scikit-learn>=1.1.2

.github/workflows/python_tests.yml, README.rst, docs/index.rst, pingouin/distribution.py, pingouin/parametric.py, pingouin/plotting.py, pingouin/tests/test_parametric.py, setup.cfg, setup.py
This PR fixes an annoying pandas 1.5+ warning, reported in #322 and #311.
I have also added Python 3.10 to unit tests
=> Fix pandas warning

pingouin/correlation.py
Fixes #340 
I added `np.clip` to `pg.corr`, right after where all the `r` values are calculated and before being passed to `power_corr`, so I think this should catch all similar cases. Rather than _always_ clipping, I only do it if the r value exceeds -1 or 1 _and_ `np.isclose` to abs(1). I don't imagine getting r values exceeding those bounds, but this felt safer to prevent accidentally clipping  something super-high down to 1.
Re-running the original code that produced the error will work now:
```python
import numpy as np
import pingouin as pg
pg.corr([1, np.nan, 2, 4], [1, 2, np.nan, 3], method='bicor')
```
=> clip r values

pingouin/parametric.py, pingouin/plotting.py
Should address #349 
I added the assertion checks right above the use of `ols` as opposed to start of each function, only because it seemed easier for a reader to extract the motivation for them. lmk if you prefer them at the top.
=> hotfix: plot_rm_corr crash with specific column names

pingouin/power.py, pingouin/tests/test_power.py
Fixes #343, caused by scipy/scipy#17916.
=> Add check for noncentrality parameters.

.github/workflows/python_tests.yml, pingouin/effsize.py, pingouin/tests/test_effsize.py
Closes #379 
Without the change, the 3.11 fails as described in issue #379 . Remaining failures are not introduced by this PR.
=> Function test fails for np.mean

pingouin/utils.py
Closes https://github.com/raphaelvallat/pingouin/issues/369
=> Fix in flatten_list for Python 3.12

pingouin/correlation.py
Thanks for the lib, small typo I found when reading the docs.
=> `corr()`: fix `CI95%` column name in returned dataframe

src/pingouin/nonparametric.py
Relates to https://github.com/raphaelvallat/pingouin/issues/417
References
- https://easystats.github.io/effectsize/reference/rank_biserial.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html
=> Fix RBC sign in mwu

src/pingouin/plotting.py
**Description:**
This pull request addresses two issues in the `plot_paired` function related to the `boxplot_in_front` parameter:
1. **Incorrect behavior when `boxplot_in_front=False`**: the boxplot was being drawn above the lines and markers even when this parameter was set to `False`, contradicting its intended functionality.
2. **Boxplot disappearance when `boxplot_in_front=False` after initial fix**:  an earlier attempt to fix the first issue resulted in the boxplot disappearing completely because its z-order was set too low.
```bash
Python 3.12.6
-------------
numpy: 1.26.4
pandas: 2.2.2
matplotlib: 3.9.2
seaborn: 0.13.2
pingouin: 0.5.5
```
**Root Cause:**
* The first issue stemmed from a lack of explicit z-order control for the boxplot elements when `boxplot_in_front` was `False`. …
=> Fix boxplot z-order in `plot_paired`

.github/workflows/python_tests.yml, docs/contributing.rst
This PR corrects a typo in the Python tests Github Action CI yaml file that was preventing the tests from running on PRs. The pingouin master branch was recently renamed from `master` to `main`, and now the yaml file reflects that. This was identified in [a comment](https://github.com/raphaelvallat/pingouin/pull/443#issuecomment-2400153386) in #443.
=> Fix the Github Action CI for Python tests

src/pingouin/parametric.py
Fix minor typo in docs (welch_anova@parametric.py): independance -> independance
=> Update parametric.py - fix typo

pyproject.toml
Summary:
* reorder `pyproject.toml` entries to make it easier to find the information.
* add `python 3.12` classifier
* remove `codecov`, `openpyxl` ~and `mpmath`~ test dependencies as they are not used in tests.
* add `extras` features to optionally install the `mpmath` dependency with `pip install pingouin[extras]`.
On a side note, `mpmath` is an optional dependency as it is checked if it's installed in `utils.py`.
It's also checked if `scikit-learn` and `statsmodels` are installed in `utils.py`, whereas they are part of the hard dependencies. Meaning they _should_ be installed, at least if installing with `pip`. These two dependencies could be moved to `extras` dependencies or the checks in `utils.py` could be removed.
=> Clean dependencies; add extras feature

src/pingouin/nonparametric.py, tests/test_nonparametric.py
Closes #456 
I had a look at providing a PR, but I am unsure if I broke more than I assumed or I am misunderstanding something. If I rerun the examples from the documentation, I get some different p-values (I updated the docs with my values in this PR) and I am seeing a test failure with just slightly mismatched values in `tests/test_pairwise.py:435`:
```E       Mismatched elements: 3 / 3 (100%)
E       Max absolute difference among violations: 0.021
E       Max relative difference among violations: 0.04347826
E        ACTUAL: array([0.912, 0.96 , 0.462])
E        DESIRED: array([0.91 , 0.951, 0.483])```
I will be able to spend some more time on this in a few days, but until then I was wondering if this might be related to a setup issue from my side you can immediately spot and help me …
=> Update RBC calculation for Wilcoxon signed-rank test to be dependent on the alternative

src/pingouin/correlation.py, tests/test_correlation.py
Before this change, `_correl_pvalue` would create a division by zero warning when r==1.
Simply adding the condition near the top of the function:
```py
if np.isclose(r**2, 1):  # Avoid divide by zero error
return 0.0  # Since p value approaches 0 as r approaches 1, just return 0
```
Fixes this. This assumes that n >= 2 since p would be undefined if n < 2, but I did not account for this case since it seems that the function already assumes that n >= 2.
Please let me know if you want me to make any other changes.
=> Fixes #453: _correl_pvalue does not divide by zero if r==1
